#!/usr/bin/env bash
set -eu

usage() {
  cat >&2 <<'EOF'
usage: render_first_operational_evidence_packet.sh \
  --output-dir <dir> \
  --track <baseline|vendor> \
  [baseline track args...]
  [vendor track args...]

This helper delegates to:
  - render_baseline_fetch_execution_packet.sh
  - render_first_actual_vendor_execution_packet.sh
EOF
  exit 1
}

require_value() {
  local name="$1"
  local value="$2"
  if [ -z "$value" ]; then
    echo "missing required argument: $name" >&2
    usage
  fi
}

SELF_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

OUTPUT_DIR=""
TRACK=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    --track) TRACK="$2"; shift 2 ;;
    *) break ;;
  esac
done

require_value "--output-dir" "$OUTPUT_DIR"
require_value "--track" "$TRACK"

mkdir -p "$OUTPUT_DIR"

case "$TRACK" in
  baseline)
    "$SELF_DIR/render_baseline_fetch_execution_packet.sh" \
      --output-dir "$OUTPUT_DIR/baseline" \
      "$@"
    ;;
  vendor)
    "$SELF_DIR/render_first_actual_vendor_execution_packet.sh" \
      --output-dir "$OUTPUT_DIR/vendor" \
      "$@"
    ;;
  *)
    echo "unsupported track: $TRACK" >&2
    usage
    ;;
esac

cat >"$OUTPUT_DIR/packet_manifest.md" <<EOF
# First Operational Evidence Packet Manifest

- Track: \`$TRACK\`
- Output Directory: \`$OUTPUT_DIR\`
- Generated By: \`render_first_operational_evidence_packet.sh\`
EOF

echo "Rendered first operational evidence packet in: $OUTPUT_DIR"
