#ifndef SIL4_STATE_MACHINE_H
#define SIL4_STATE_MACHINE_H

#include <stdint.h>

#define D_SIL4_ACTION_CAPACITY (4U)

typedef enum
{
	SIL4_STATE_UNINITIALIZED = 0,
	SIL4_STATE_INITIALIZED,
	SIL4_STATE_CONNECTING,
	SIL4_STATE_ESTABLISHED,
	SIL4_STATE_RETRANSMISSION_PENDING,
	SIL4_STATE_SAFE_DISCONNECT,
	SIL4_STATE_SHUTDOWN,
	SIL4_STATE_INVALID
} sil4_state_t;

typedef enum
{
	SIL4_EVENT_INIT_SUCCESS = 0,
	SIL4_EVENT_INIT_FAILURE,
	SIL4_EVENT_CONNECT_REQUEST,
	SIL4_EVENT_VALID_INBOUND_CONNECT,
	SIL4_EVENT_HANDSHAKE_SUCCESS,
	SIL4_EVENT_VALID_HEARTBEAT,
	SIL4_EVENT_VALID_DATA,
	SIL4_EVENT_SEQUENCE_GAP_DETECTED,
	SIL4_EVENT_RECOVERY_SUCCESS,
	SIL4_EVENT_DISCONNECT_REQUEST,
	SIL4_EVENT_TIMEOUT,
	SIL4_EVENT_INVALID_MESSAGE,
	SIL4_EVENT_VERSION_MISMATCH,
	SIL4_EVENT_PROTOCOL_ERROR,
	SIL4_EVENT_RETRANSMISSION_FAILURE,
	SIL4_EVENT_INVALID_RESPONSE,
	SIL4_EVENT_SHUTDOWN_REQUEST,
	SIL4_EVENT_CLEANUP_COMPLETE,
	SIL4_EVENT_INVALID
} sil4_event_t;

typedef enum
{
	SIL4_ACTION_NONE = 0,
	SIL4_ACTION_START_HANDSHAKE,
	SIL4_ACTION_ACCEPT_INBOUND_CONNECT,
	SIL4_ACTION_START_SUPERVISION_TIMER,
	SIL4_ACTION_RESET_SUPERVISION_TIMER,
	SIL4_ACTION_SEND_HEARTBEAT,
	SIL4_ACTION_DELIVER_DATA,
	SIL4_ACTION_REQUEST_RETRANSMISSION,
	SIL4_ACTION_CLEAR_RETRANSMISSION_CONTEXT,
	SIL4_ACTION_SEND_DISCONNECT,
	SIL4_ACTION_ENTER_FAILSAFE,
	SIL4_ACTION_LOG_DIAGNOSTIC,
	SIL4_ACTION_RELEASE_CONNECTION_RESOURCES,
	SIL4_ACTION_NOTIFY_API,
	SIL4_ACTION_FINALIZE_SHUTDOWN
} sil4_action_t;

typedef enum
{
	SIL4_STATUS_OK = 0,
	SIL4_STATUS_INVALID_ARGUMENT,
	SIL4_STATUS_INVALID_EVENT,
	SIL4_STATUS_INVALID_STATE,
	SIL4_STATUS_REJECTED
} sil4_status_t;

typedef struct
{
	sil4_action_t eActions[D_SIL4_ACTION_CAPACITY];
	uint32_t uActionCount;
} sil4_action_list_t;

typedef struct
{
	sil4_state_t eCurrentState;
	sil4_status_t eLastStatus;
	uint32_t uEventCounter;
} sil4_state_machine_context_t;

typedef struct
{
	sil4_state_t ePreviousState;
	sil4_state_t eNextState;
	sil4_status_t eStatus;
	sil4_action_list_t xActions;
} sil4_transition_result_t;

sil4_status_t state_machine_init(
	sil4_state_machine_context_t * pxContext);

sil4_status_t state_machine_handle_event(
	sil4_state_machine_context_t * pxContext,
	sil4_event_t eEvent,
	sil4_transition_result_t * pxResult);

sil4_state_t state_machine_get_state(
	const sil4_state_machine_context_t * pxContext);

sil4_status_t state_machine_reset(
	sil4_state_machine_context_t * pxContext);

#endif

